### PR TITLE
Add project, mikaelacaron

### PR DESCRIPTION
**Pull request by mikaelacaron**
Job Application Tracker

### CODE REVIEW

**Review by ScottKwang — APPROVED** [review]
Really enjoyed the insta stories! I think I only saw `UIKit` in your posts, did you try out any `SwiftUI` like Mayuko?

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Comment by mikaelacaron** [comment]
@ScottKwang I decided to use UIKit for this project because I'm hoping to release it to the App Store soon!
I'm more familiar with UIKit, maybe later I'll make it SwiftUI

**Comment by hellomayuko** [comment]
Wow great job @mikaelacaron !!!! Love the app, I can't wait for it to be in the App Store! My job hunting friends could totally make good use of this.

**Comment by mikaelacaron** [comment]
Thanks @hellomayuko ❤️

**Pull request merged**
