### PR TITLE
Book-saver - Stop letting books pile up  unread!

### PR DESCRIPTION
**Pull request by yuhijackman**
Hello Scott and Mayuko!
This is my project for Code with Friends Spring 2020.

# Overview
A visual reminder of how much unread books on your bookshelf are worth and helps you stop letting books pile up unread.

# Link to this project
https://brave-chandrasekhar-d3acfd.netlify.app/

# Demo account
You can try it out with this account.
Email: demo@gmail.com
Password: Demoaccount

### CODE REVIEW

**Review by hellomayuko — APPROVED** [review]
Haha, I love this!!! I have so many books piling up at home, that this would be so useful for me! 

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Comment by hellomayuko** [comment]
Oops, looks like there's a merge conflict. Do you mind fixing that up? Otherwise we're all good to merge.

**Comment by hellomayuko** [comment]
I just added the .DS_Store to our .gitignore, so if you merge in master onto your branch, it should work!

**Comment by yuhijackman** [comment]
I'm so sorry to mess up git history. I couldn't merge in master onto my branch so I needed to figure out a different way.

**Comment by yuhijackman** [comment]
I really appreciate for your review and I filled out the form.
Thank you for holding this fun and awesome event once again.
I could feel like we all who joined this event are building apps together and walking toward the same goal and this feeling made creating this project way more fun.

**Review by ScottKwang — APPROVED** [review]
Very nice! Hope you enjoyed working on this project. I really like the concept and execution! I am definitely very bad about keeping up with the books I want to read.

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Pull request merged**
