### PR TITLE
code with friends entry: SpesApp

### PR DESCRIPTION
**Pull request by harisont**

### CODE REVIEW

**Review by hellomayuko — CHANGES_REQUESTED** [review]
Very cool! I like the idea of keeping track of what you have in the fridge too, to reduce waste. Do you mind linking your project's README in the README you're committing? Also, if you could help me resolve the merge conflict, that'd be great.

**Comment by harisont** [comment]
No problem, done :)

**Review by hellomayuko — APPROVED** [review]
Looks great! Thanks @harisont!

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Comment by hellomayuko** [comment]
Oops, looks like there's a merge conflict. @harisont do you mind resolving it? Thanks!

**Pull request merged**
