### PR TITLE
CWF Submission!

### PR DESCRIPTION
**Pull request by alacau**

### CODE REVIEW

**Review by hellomayuko — CHANGES_REQUESTED** [review]
Alan, thanks for submitting a project! Can you make your own project subdirectory and add your own README, rather than editing the one that's already there? Also, it looks like all of your README links are broken. If you could also add one line about what the app actually is, that'd be great!

**Comment by Alacau** [comment]
I think I fixed all the links and updated the README.md a little and also added my project files into a subdirectory!

**Comment by hellomayuko** [comment]
Hey @Alacau, your `README.md` still isn't in that folder you made. Can you fix?

**Comment by ScottKwang** [comment]
Thanks for being a part of CWF, and congrats on your project!
Even if we aren't able to merge your project by Monday make sure to fill out this form by then to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Comment by Alacau** [comment]
Sorry about that I was just confused. README.md added!

**Pull request closed without merging**
