### PR TITLE
CWF Submission - Digital Window! 💻⛅🌳

### PR DESCRIPTION
**Pull request by sttic**
Thank you two for being an inspiration and running a fun event like this!

---
# Digital Window

Created by

- Tommy Deng ([sttic](https://github.com/sttic) on GitHub)
- Vivian Diec ([viviandiec](https://github.com/viviandiec) on GitHub)

Source code: https://github.com/sttic/CodeWithFriends-Spring2020

Digital Window is a submission for the [Code With Friends - Spring 2020](https://cwf.hellomayuko.com/) event by Mayuko Inoue and Scott Kwang.

## Summary

Digital Window aims to mimic a real window in situations where they are not available. It does so by transitioning between different images of the day depending on the current time.

A key feature is that it adjusts your display's backlight brightness, as in brightening or dimming your screen. This is better than just adding filters or doing any software adjustment to an image because this physically changes the amount of light being produced. Changing the backlight makes showing a true fully black screen possible on a common LCD display (turning it off to 0% brightness late at night) while still allowing it to be turned back up to maximum brightness during the day.

dynamic-background

_Screen capture of crossfading background from the project (video is sped up). Backlight dimming can't be seen with this._

actual-appearance

_Actual appearance of screen, with backlight dimming, recorded on a phone (video is sped up even more). Dimming/brightening is reduced in the recording because of auto-exposure. Notice the screen getting dark and turning off and back on._

Original art is [Lakeside by Louis Coyle](https://dynamicwallpaper.club/wallpaper/jculsb683ok).

This is a web app meant to be ran locally on your machine. It's recommended to set your browser to fullscreen while this is active. It is built with [Next.js](https://nextjs.org/) and [Node.js](https://nodejs.org/). The project requires the [xbacklight command](https://linux.die.net/man/1/xbacklight) and was tested on Manjaro Linux.

### CODE REVIEW

**Review by ScottKwang — APPROVED** [review]
Woahh I really like this concept, very clean! Did you both try having it on a monitor throughout the day? Glad you were able to find time to work on it during your internships! Hope going with it even after CWF is over!

Thanks for being a part of CWF, and congrats on your project!
Fill out this form by Monday to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Comment by sttic** [comment]
Thank you Scott! We were working on it pretty late and only got it fully working today, so we only saw it under sped up time so far :sweat_smile:. We're trying it for real tonight and onwards!

Thank you again for hosting this event along with Mayuko! Looking forward to see what you guys do next :heart:

**Comment by hellomayuko** [comment]
Okay this is seriously so cool!!! Hi Vivian and Tommy, thanks for being a part of the event!! Great job you two!

**Comment by ScottKwang** [comment]
Also. I 100% blame you guys. I haven't been "to work" since we went to CUSEC.

**Comment by viviandiec** [comment]
Hi Mayuko and Scott!! Thanks so much for hosting this incredible event 🤩 We had so much fun!

**Pull request merged**
