### PR TITLE
created my project setup!

### PR DESCRIPTION
**Pull request by Vladislav0Art**
I created a new folder called TommyIQ in projects/ directory, added README and uploaded files of my project.

### CODE REVIEW

**Review by hellomayuko — COMMENTED** [review]
Hi Tommy! Do you mind telling me a bit more about what the app is on the README? It also looks like your screenshots are broken, if you want to fix that before I merge!

**Comment by TommyIQ** [comment]
Basically it is an application where people can share any files they want with other users (you can view it following the link to deployed app).

Clients can find each other by searching for the user by his name, then they can write them a comment in private chat and ask for the id (this id allows to find the account's files), after getting the id the user can find the files and download or view them in the browser.

Sorry for the broken images, I don't know  exactly how to do make them work correctly, so it is fine to merge it like that)

P.S. Sorry if I write a bit weird)

**Comment by hellomayuko** [comment]
That's great @TommyIQ , can you add that into the `README.md` file itself?

**Comment by ScottKwang** [comment]
Thanks for being a part of CWF, and congrats on your project!
Even if we aren't able to merge your project by Monday make sure to fill out this form by then to receive your sticker in the mail! https://forms.gle/zy6nr8czF4uoRA4j9

**Pull request merged**
